run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - misspell
    - unconvert
  disable:
    - exhaustive # too noisy for switch statements

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: false
  unused:
    check-exported: false

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
